# MySQL
spring.datasource.url=jdbc:mysql://localhost:3306/testdb
spring.datasource.username=test
spring.datasource.password=test

# JPA
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=validate

# Logging
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE